### ISSUE TITLE
Lyrics grabbing support

### ISSUE THREAD

**Issue by jacktheripper19** [tesshucom/jpsonic#1335]
### Describe the solution you'd like
When listening to music, the user might want to follow along with the lyrics to learn the lyrics and enjoy the song more.
It would be great to have the server grab the lyrics from sources like uta-net or other sources that provides .lrc synced lyrics.

*A clear and concise description of what you want to happen.*
scan all songs in the library, make requests to suitable sources for lyrics, add them to the tags of the songs or as .lrc files in the same folder as the song.

### Describe alternatives you've considered
I considered using beets that has an alternative since it has a lyrics plugin but that one pull from google, genius and other resources that are not in japanese (sometimes you get the translated lyrics or the romaji version), so even if the upstream implement this feature it wont take this into account. It is also a pain to set up and bundle with other music servers, especially if using docker containers.

**Comment by tesshucom** [comment]
In Japan, Smartphones are the most common terminals used to listen to music on the cloud. Next are laptops, tablets, and desktops. The number of users of smart speakers is a minority. Therefore, Jpsonic does not reuse all the features of Airsonic as it is, but the functions are reconfigured for Japanese people. Instead of removing Sonos, for example, UPnP has been completely reimplemented, and high resolution sound quality was supported. The aim is to allow users to select more smartphone apps.
___

Thank you for your opinion. Perhaps the feature is available if you implement it according to your idea. On the other hand, there may be other modern solutions as well. 

One of [Airsonic's policies](https://github.com/airsonic/airsonic/projects) is as follows :

> #### All external integrations are optional
> Make it possible (but not mandatory) to run airsonic without an internet connection: all the resources are self-hosted.

The reason for recommending this is not clearly stated, but I agree. This is because the functions realized by using external services can often be solved by smart device apps. In fact, we can see it on [Google play](https://play.google.com/store/search?q=lyrics&c=apps). For example, [Walkman Lyrics Extension](https://play.google.com/store/apps/details?id=net.akihiro.walkmanlyricsextension) is relatively good for searching Japanese songs. You can display lyrics in the float window by linking with other music apps.

<img src="https://user-images.githubusercontent.com/27724847/152182431-eb7e90df-5c8d-46d9-a485-0ef3d08eafb5.png" height="200px">

It seems that you can switch between language and translation.

> The lyrics language supports the following 7 languages.
> English, Japanese, Chinese, 한국, Bahasa Indonesia, Español, Português, Nederlands, Русский, Italiano
> In addition, there is a function to pass the displayed lyrics to the translation service.

Acquisition of lyrics and acquisition of artist images are functional fields that are being developed in smart device apps in recent years. Therefore, we may avoid reinventing the wheel and concentrate development resources on solving the original problem of the server.
If you want to use the collected text for some secondary purposes, such as using it for some statistics, your idea will surely be advantageous. However, I think the discussion of such use cases is probably a little different from the original purpose of the server.
