### ISSUE TITLE
 Improvement of Japanese search accuracy

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#177]
In Refactoring of #161, some functions have been simplified by giving priority to bug fixes and class separation.

#### Wildcard improvement
Legacy servers were string combining asterisks.
(Including useless fields)
Add wildcards to the required items by the filter. There is no concern about performance because it is a small index.

#### Avoid duplicate registration
Currently, there are fields to complement the accuracy of Japanese search.
These are simply populated with database data at index creation time.
Things that seem to overlap in content will be improved to not register.
This will reduce index data somewhat.

#### Japanese completion extension
Extend some of the measures taken against the artist to albums and songs.
What is particularly weak in natural language processing in Japanese is the phrase of only hiragana.
Since it is nonsense to solve this academically, we modify it so that it is linked to Doc only if the input value for the field consists of only hiragana characters.
This will increase the index data somewhat. However, considering common sense, the target case is not so common and does not have the size that puts pressure on the system.

**Comment by jp-searching** [comment]
The contents of analysis are different for each field.
Defined in Analyzer.

 - Normal analysis              - Normal tokenizing and filtering
 - Other than Normal analysis   - No tokenize, special filtering

Asterisk is unconditional registration.
Otherwise, perform conditional registration considering the importance of data and the amount of data.

| FieldName| 
Contents of registration data|
----|---- 
| ARTIST| * Normal analysis |
| ARTIST_FULL| Registration when other than hiragana (possibility of various character types)|
| ARTIST_READING| * Sort key (possibility of various character types)|
| ARTIST_READING_HIRAGANA| Convert to Hiragana and register|
| ALBUM| * Normal analysis|
| ALBUM_FULL| Registration when other than hiragana|
| ALBUM_READING_HIRAGANA| Register when hiragana only|
| TITLE| * Normal analysis|
| TITLE_FULL| xxxxxx Do not register (consider the amount of data) |
| TITLE_READING_HIRAGANA| Register when hiragana only|

Hiragana's prefix match is very important because Japanese is always input from Hiragana in IME input.
Unless you copy and paste, you will always go through hiragana before kanji and katakana.

**Comment by tesshucom** [comment]
The analyzer does not support the above specifications.
It needs to be fixed.
