### ISSUE TITLE
Index generation change is not working

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#217]
The generation change of DB schema definition is fully functional.
The lucene index generation alternation logic exists in MediaScannerService but it seems to be nonfunctional.
(Probably not working with Airsonic too?)

Rewrite if necessary.
___

Legacy is managing by schema version.
lucene has experienced that the implementation difference by version is very large.
Therefore, the management version should be clarified with index implememt version + schema version.

**Comment by jp-searching** [comment]
The will be following corrections are made.

#### MediaScannerService#deleteOldIndexFiles()

Since this method is the starting point of the increment process, modify the subsequent process of this method.

#### Schema management

Add version method to DocumentFactory and IndexType.

https://github.com/tesshucom/jpsonic/commit/bbeac4f51f12c93e2e95e95e5ac1203641272869

###### IndexType.
Field is managed. The concept is close to the DB column.
###### DocumentFactory
Document definition is managed. The concept is close to the DB definition.
Implementation strongly depends on product and version used for search.

For continual maintenance, version upgrades, and feature additions.
The idea of ​​identifying a revision by combining the above two classes version with the product version of the search library used may be easy to accept.

**Comment by jp-searching** [comment]
Subsonic's file delete is probably implemented assuming a single file.
(lucene2.x???)
The implementation seems to have abandoned maintenance.
