### ISSUE TITLE
Left sidebar/drawer always opened

### ISSUE THREAD

**Issue by Tak-MK** [tesshucom/jpsonic#2647]
### Is your feature request related to a problem? Please describe.

Not really a problem, just a UI/UX preference. In my case it's because I use the left drawer and the settings option way often but everytime I login or reload it closes automatically.

### Describe the solution you'd like

I'd like to have the left side (drawer + user box) always opened (screenshot attached).

### Describe alternatives you've considered

Having an option in Settings->Personal->Drawer as "Always opened" or similar.

### Additional context

![Jpsonic_と_tmux](https://github.com/tesshucom/jpsonic/assets/6209766/ebc68eeb-36b6-428a-9903-f4b745a878c6)

Thanks!

**Comment by tesshucom** [comment]
I know what you're saying. Still, web front ends are not currently a high priority issue. There may or may not be any modifications made in the future. The menu structure itself is scheduled to change in v114.

___

Most of the current framework is diverted from Airsonic. Of course, that's an excuse, and I realize that if you want a better UI, it's better to redesign everything. Skill set-wise, I've got it covered. Or you can replace it with some kind of web framework. Whatever it is. (In my third year in this industry, I was supervising the web front-end implementation for a project with less than 100 people. Although it was more of a native app.)

As I may have mentioned before, this project does not neglect the web front end, but rather emphasizes the back ground process. Streaming servers do not necessarily require a web front end. (You may also know that there are media servers with such a configuration.) If we want to move forward, I just need to have the spare time for that, or find another Ace programmer who can focus on the web page.

There are many projects that fail due to half-hearted efforts to create a web page, right? That path must be avoided at all costs.　This is just a prediction based on my estimate... The calculation of man-hours is incorrect. Replacing the entire web screen would require a significant amount of time and effort.(Of course, there is no reward there.) In reality, backend maintenance will probably require several times that amount.

The same can be said for partial fixes. If we're going to spend time on it, there are probably more important tasks on the Background side.

___

Fortunately, you can do a lot of things via the Subsonic API. Have you looked for web apps that can meet your requirements? Perhaps you can get a better response if you suggest a feature improvement to the developer of that app. This is not an attempt to shift responsibility; it is because Subsonic was originally created with this idea in mind. It can be a web app or a smartphone app, but please consider using it in combination with both.

**Comment by Tak-MK** [comment]
Sincerely I think I either explained it wrongly or you got a wrong idea…
sorry just in case.

I don’t think what has the Subsonic API has to do with just keeping the
left drawer opened, there’s even an option in jpsonic to auto-close it.
Also, Subsonic developer disappeared many years ago, but still has nothing
to do with this.

I’m knowledgeable in some frontends or apps using the API as a backend, and
providing a different way of interacting with the server, but what I just
asked was an extra option in the same way you added it time ago, not an
entire new functionality.

And obviously I get that redoing the frontend is less important than fixing
everything in the backend, but let’s agree that comparing redoing the web
UI vs what I’ve asked about it’s really far away…

Thanks!

2024年5月21日(火) 18:45 tesshu.com ***@***.***>:
