### ISSUE TITLE
DLNA folder expansion is too slow

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#310]
Need to be improved because deployment of Filestructure directory is very slow in DLNA.

#305

**Comment by tesshucom** [comment]
It may require a little effort..

**Comment by tesshucom** [comment]
It may be resolved in #318.

**Comment by jp-sorting** [comment]
Removed cache and implemented asynchronous search.
Speed ​​is dramatically improved.

Strictly speaking, a cache is required by design.
However, it is impossible to use legacy low quality cache.
Also, overflow due to multiple sessions is a low risk as a practical problem.
It works with no cache for a while and sees the progress.

I made a fix for three processors, but I will try this fix for all processors.

- [ ] ArtistUpnpProcessor
- [ ] AlbumUpnpProcessor
- [ ] MediaFileUpnpProcessor
- [ ] GenreUpnpProcessor
- [ ] PlaylistUpnpProcessor
- [ ] RecentAlbumUpnpProcessor

**Comment by jp-sorting** [comment]
Removed cache and implemented asynchronous search.
Speed ​​is dramatically improved.

Strictly speaking, a cache is required by design.
However, it is impossible to use legacy low quality cache.
It works with no cache for a while and sees the progress.
If overflow from multiple sessions is a threat, a better cache needs to be implemented.

I made a fix for three processors, but I will try this fix for all processors.

- [x] ArtistUpnpProcessor
- [x] AlbumUpnpProcessor
- [x] MediaFileUpnpProcessor
- [ ] GenreUpnpProcessor
- [ ] PlaylistUpnpProcessor
- [ ] RecentAlbumUpnpProcessor
