### ISSUE TITLE
 Migration test

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#311]
- [x] Checking the index and DB version
 - [x] Delete old index
 - [x] The path sorting has been modified. Check if there is any problem migrating from old scanned data
 - [x] ~~Rethink sorting options. If the speed improvement benefit from the strict sorting option is small, the setting item on the screen side is omitted at this stage. If the scope of speed measures expands in the future, it will be revived.~~
 - [x] Get help on sort options

**Comment by tesshucom** [comment]
Sorting option must be released. The speed does not change much, but UPnP's ID3 sorting will not work correctly unless you specify an option.

**Comment by tesshucom** [comment]
Pick up small localization work left in the presentation, including help, and draft another issue.

**Comment by tesshucom** [comment]
![image](https://user-images.githubusercontent.com/27724847/66773981-5ca48a80-eefb-11e9-9cbd-49ed6a7e55d5.png)

**Comment by data-struct** [comment]
Currently,
 - reading contains tags or analysis results of name
 - sort contains tags

Both are nullable by definition.
However, reading is generated almost at the same time as name, and is effectively not null (you can add a null constraint)

The current situation is the result of a series of specification changes.
At the moment there is no inconsistency in the test case itself.

On the other hand, there may be null readings on the system database that has been updated since the initial release.
The Nullpointer above shows the existence of such a record.
___

It can be solved by deleting legacy inconsistent data that cannot be created now.
Since it is released at the same time as the data version increment, the correct data is created by the full scan.
