### ISSUE TITLE
Missing case of sort test

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#380]
Insufficient testing when the name is (full-width / half-width) alphabet and reading is Japanese.
This is a relatively uncommon use case, but may be necessary when using voice input.

 - Some sorts do not sort correctly
 - Sorting cannot be correctly performed in a sort implementation that depends only on Colator instead of Comparator

The following actions are required: 

 - Adding test data
 - Modify existing logic
 - Consider design change of Index generation

**Comment by tesshucom** [comment]
#376 first.
Next, create a decision table and perform exhaustive testing.

**Comment by jp-sorting** [comment]
> Add the case of DB-sorting because it is not enough.

New test class added, and three places have been fixed.
The fix for JapaneseReadingUtils is a fix for the issues pointed out in this issue.

JpMediaFileComparator and JpsonicComparators have been modified to match legacy code.
However, it will not affect the operation specifications with actual data.

**Comment by jp-sorting** [comment]
> Add the case of DB-sorting because it is not enough.

New test class added, and three places have been fixed.
The fix for JapaneseReadingUtils is a fix for the issues pointed out in this issue.

The fix for year have been modified to match legacy code.
However, it will not affect the operation specifications with actual data.

The data version has been incremented because the data washing process may be affected depending on the data content

**Comment by tesshucom** [comment]
Added because the case is insufficient.

**Comment by tesshucom** [comment]
The ID3 side can sort correctly, but "ALL" in the file structure does not work correctly.
Check and fix.

**Comment by jp-sorting** [comment]
Correct the test data because it is wrong.

**Comment by jp-sorting** [comment]
``Web: Hom > All`` fixes.

When sorting by artist, if "MediaType = DIRECTORY" and "non-artist" data are included, the artist may not be sorted correctly.
To fix this problem, you need to fix Dao instead of Comparator.

**Comment by tesshucom** [comment]
Confirmed the fix.
