### ISSUE TITLE
Change data specifications(DB)

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#406]
Modify some column specifications and add new columns to make it easier to create checkers later.
(Or to make it easier for users to create SQL queries.)

No additional data is required for system main functions(sorting, searching).
But the checker function is expected to have a need.

#### Purpose , Advantage

- Make it easy to create checkers.

#### Disadvantage

DB data increases a little.
Properties is added to the domain object.
Requires at least three extra columns at media_file.

___

Jpsonic has added three columns.
_order, *_ reading, *_ sort.

column | remarks
-- | --
_order | It's sort numbers for each artist and album considering English and Japanese. Generated from *_reading. Required for SORT-ALL and UPnP. The use of this is optional, but without it, it is not possible to provide a common SORT on every DB.
*_reading | Sort key used for sorting only. This is a string that is determined by the system as a whole and is a mandatory field. If sorted by Java instead of DB, it can be handled properly.
*_sort. | The word readings for pass to Lucene. Compensation for null data is performed to prevent dropout of search.

The current analysis result is machine readable.
You can create sort and search indexes.
However, the value stored in the DB is a little different from the string that the user expects.

Modify as follows :

 - [x] Add a column that keeps simple the original data.
 - [x] Slightly reduce the *_sort-tag normalization process.To make it easier to compare with the original data. Does almost the same processing in Lucene so does not affect search.
 - [ ] Improve cumulative scans of records with multiple readings(edge case).

**Comment by tesshucom** [comment]
> Investigate whether normalization processing for DB sort columns can be eliminated.
> And examine whether the scanned tag values ​​can be stored in the DB as they are.

In situations where the number of songs cannot be predicted, very inefficient, if not impossible.
Because after registering after cleansing, the comparison is performed by SELECT in DB.
Scanning recursively with additional data degrades at an accelerated rate.

It is easier to store the original data in a separate column.

#### advantage

More easy to make checkers.

#### Disadvantage

DB data increases a little.
Properties is added to the domain object.
Requires at least three extra columns at media_file.

**Comment by tesshucom** [comment]
What was broken was my local data ...

**Comment by tesshucom** [comment]
Improves cumulative scanning of records with multiple readings.
If solvable without referencing the original data, do so.
(Do not refer to the original data at the time of update processing. The original data is used only at the time of SELECT of the check)

**Comment by data-struct** [comment]
HSQLDB may not be able to handle complex SQL due to strange alias reference specification.

**Comment by data-struct** [comment]
Seems to have some issues.

 - (1) Since the reference specification of the alias differs depending on the DB, it takes a little time to create and confirm a complicated SQL.
 - (2) There is doubt about the original scan specification. The interpretation of the album-artist is somewhat special. I checked the history, but it seems to be the current specification from the beginning of Airsonic.

The solution for (2) is desirable, but the conclusion is postponed.
First, we will change to a more convenient function that is safer for existing specifications.

Focus on solving (1).
Change to the correction process involving the composer.
In recursive updating, change to a correction process that easily reflects the user's intention.

**Comment by tesshucom** [comment]
Seems to have some issues.

 - (1) There is doubt about the original scan specification. The interpretation of the album-artist is somewhat special. I checked the history, but it seems to be the current specification from the beginning of Airsonic.
> In MetaDataParser # L56-L57, the logic of Artist of Filestructure is used instead of logic of AlbumArtist, so wrong value may be forced. This is a process that assumes that the Album directly under Artist has the same AlbumArtist instead of null. (Because it is essentially impossible to judge here, it is a solid specification or bug). Current spec, we create a derivative case of AlbumArtist and AlbumArtistSort. To be precise, current scans cannot always guarantee the consistency between AlbumArtist and AlbumArtistSort.
 - (2) Since the reference specification of the alias differs depending on the DB, it takes a little time to create and confirm a complicated SQL.



Verification is required for (1).
It is regarded as a bug or a strange specification, but if it can be handled properly, switching with options is appropriate.

(2) is a technical problem, but depending on the approach to (1), there are some ways to deal with it.

**Comment by tesshucom** [comment]
Improves cumulative scanning of records with multiple readings.
If solvable without referencing the original data, do so.
(Do not refer to the original data at the time of update processing. The original data is used only at the time of SELECT of the check)

___


Seems to have some issues.

 - (1) There is doubt about the original scan specification. The interpretation of the album-artist is somewhat special. I checked the history, but it seems to be the current specification from the beginning of Airsonic.
> In MetaDataParser # L56-L57, the logic of Artist of Filestructure is used instead of logic of AlbumArtist, so wrong value may be forced. This is a process that assumes that the Album directly under Artist has the same AlbumArtist instead of null. (Because it is essentially impossible to judge here, it is a solid specification or bug). Current spec, we create a derivative case of AlbumArtist and AlbumArtistSort. To be precise, current scans cannot always guarantee the consistency between AlbumArtist and AlbumArtistSort.
 - (2) Since the reference specification of the alias differs depending on the DB, it takes a little time to create and confirm a complicated SQL.


Verification is required for (1).
It is regarded as a bug or a strange specification, but if it can be handled properly, switching with options is appropriate.
Alternatively, send bug fixes to Airsonic and fix them from the ground up.

(2) is a technical problem, but depending on the approach to (1), there are some ways to deal with it.

___

The verification in (1) should take precedence.

**Comment by data-struct** [comment]
Preserve the specifications of (1).
The reason is that  : 
it is possible to set a different album artist for the files in the album due to data specifications, but it is an edge case in actual operation.

However, in the current situation (in the case of an edge case library), overwriting album artists may destroy the consistency of album-artists and album-artist-sorting.
Therefore, if you change the current guess specification and overwrite AlbumArtist, modify it so that AlbumArtistSort is also changed at the same time.
If you do not do this, if the album has more than one album artist, the reading completion process will not work.

**Comment by tesshucom** [comment]
Hot fix rebase

**Comment by tesshucom** [comment]
This commit broke Travis.
![image](https://user-images.githubusercontent.com/27724847/77219124-e412bb80-6b75-11ea-8457-7570e4102f97.png)
Nice.

**Comment by data-struct** [comment]
![image](https://user-images.githubusercontent.com/47806602/77231055-d55eef80-6bdb-11ea-8870-b6f094586ce3.png)
As with last year's large disability, becoming more load-sensitive.
For some time, an error may occur in a test that is not a problem in some cases.

**Comment by data-struct** [comment]
Changed the specification for cleansing dirty data.
The specification to update the artist sort tag will be changed.

Priority is set when merging duplicate tags.

- The highest priority is the file date
- If the dates are equal, AlbumArtist > Artist > Composer take precedence

This is in an order that reflects the intentional modification of the user.

 - Merge if the reading for the person name is duplicated
 - If missing tags exist after merging, copy from merged data
 - If copying the missing part does not help, in other words if the tag does not resolve the reading, perform a Japanese analysis on the server

**Comment by data-struct** [comment]
The specification to update the album sort tag will be changed.

Albums are not so difficult because they don't have as many items as people.
The priority is date only.
However, like artist, it uses a three-step process of merge/copy/compensation.
Because maintainability is high.

**Comment by tesshucom** [comment]
Rebase and merged.
